- name: Disable IPV6
  hosts: '{{ grp }}'
  tasks:
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: "present"
        reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "0"
        state: "present"
        reload: "yes"
      with_items:
        - net.ipv6.conf.all.autoconf
        - net.ipv6.conf.default.autoconf
